### ISSUE TITLE
The eds example doesn't seem to work

### ISSUE THREAD

**Issue by syvanpera** [bggardner/canopen-rpi#3]
Trying to run the canopen-node-eds example and getting the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/canopen-rpi/socketcanopen/node.py", line 1369, in reset_communication
    self.od.update({odi: obj})
  File "/home/pi/canopen-rpi/socketcanopen/object_dictionary.py", line 380, in update
    self[index] = obj
  File "/home/pi/canopen-rpi/socketcanopen/object_dictionary.py", line 365, in __setitem__
    raise TypeError("CANopen object dictionary can only consist of CANopen Objects")
TypeError: CANopen object dictionary can only consist of CANopen Objects
```

**Comment by bggardner** [comment]
Fixed in 9de08e2
